site_name: Project SOTAS
site_url: https://projectsotas.github.io/documents/

theme: 
  name: material
  locale: en
  language: en

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    
  palette:
    scheme: default
    primary: cyan
    accent: yellow


docs_dir: ./docs
site_dir: ./build

strict: true

extra:
  generator: false

repo_url: https://github.com/ProjectSOTAS
repo_name: Project SOTAS
edit_uri: documents/blob/master/docs/
