site_name: Project SOTAS
site_url: https://projectsotas.github.io/

theme: 
  name: material
  locale: en
  language: en

  # logo: logo.png
  # favicon: ../assets/logo.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    # - navigation.indexes
    - navigation.top

  palette:
    scheme: default
    primary: cyan
    accent: yellow


docs_dir: ./docs
site_dir: ./build

strict: true

markdown_extensions:
    - toc:
        separator: "_"

extra:
  generator: false

repo_url: https://github.com/ProjectSOTAS
repo_name: Project SOTAS
edit_uri: documents/blob/master/docs/
