site_name: Project SOTAS
site_url: https://sotas.github.io/
theme: 
  name: material
  locale: en
  language: en

  logo: sotasDocs/assets/logo.png
  favicon: sotasDocs/assets/logo.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    # - navigation.indexes
    - navigation.top


  palette:
    scheme: default
    primary: cyan
    accent: yellow

docs_dir: ../

strict: true

markdown_extensions:
    - toc:
        separator: "_"

extra:
  generator: false

repo_url: https://github.com/ProjectSOTAS
repo_name: projectSOTAS
edit_uri: documents/blob/master/
